; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32_v2]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
lib_deps =
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
    adafruit/Adafruit NeoPixel@^1.12.3
    sparkfun/SparkFun LIS2DH12 Arduino Library@^1.0.3
    sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library@^1.0.4
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libhelix.git
    https://github.com/tzapu/WiFiManager.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/dismonio/ReactionTimeGame.git
    #https://github.com/dismonio/SimonSaysGame.git
    lib/PixelWaterfallGame
    lib/SPHFluidGame
    lib/BreakoutGame
    lib/SimonSaysGame


# Custom configurations
build_flags = 
    -DCORE_DEBUG_LEVEL=5 # Verbose Core Debug Level
board_build.partitions = default_8MB.csv # Partition Scheme: 3MB APP/1.5MB SPIFFS
board_build.flash_mode = qio
board_build.f_cpu = 240000000L # CPU Frequency: 240MHz (WiFi/BT)
board_build.flash_freq = 80000000L # Flash Frequency: 80MHz
board_build.flash_size = 8MB # Flash Size: 8MB (64Mb)

upload_speed = 921600 # Upload Speed
board_build.psram = enabled # PSRAM: Enabled

# Optional: Disable Zigbee mode (custom flag if needed in your project)
#build_flags += -DZIGBEE_DISABLED

# Enable verbose output for debugging
monitor_speed = 115200